
// This file has been generated by the GUI designer. Do not modify.
namespace Integrativa
{
	public partial class ConsultarProducto
	{
		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Integrativa.ConsultarProducto
			this.Name = "Integrativa.ConsultarProducto";
			this.Title = global::Mono.Unix.Catalog.GetString("ConsultarProducto");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
